version: 0.2
env:
  parameter-store:
    DOCKERHUB_USERNAME: "[user-name]"
    DOCKERHUB_PASSWORD: "[password]"
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-2)
      - chmod +x gradlew
      - ./gradlew --daemon
      - ECR_REPO=415353467794.dkr.ecr.us-east-2.amazonaws.com
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - uname -a
      - java --version
      - docker --version
      - ./gradlew bootjar
      - docker build -t rmm-order-service:latest .
      - docker tag rmm-order-service:latest $ECR_REPO/rmm-order-service:latest
      - docker images
  post_build:
    commands:
      - docker push $ECR_REPO/rmm-order-service:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' "rmm-order-service" "$ECR_REPO/rmm-order-service:latest" > imagedefinitions.json
      - ls -la
artifacts:
  files: imagedefinitions.json
