version: 0.2
phases:
  pre_build:
    commands:
      - echo Entering the pre_build phase...
      - $(aws ecr get-login --no-include-email --region us-east-2)
      - chmod +x gradlew
      - ./gradlew --daemon
      - ECR_REPO=415353467794.dkr.ecr.us-east-2.amazonaws.com
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Entering the build phase...
      - uname -a
      - java --version
      - docker --version
      - ./gradlew bootjar
      - docker build -t om-service:latest .
      - docker tag om-service:latest $ECR_REPO/om-repository:latest
      - docker images
  post_build:
    commands:
      - echo Entering the post_build phase...
      - docker push $ECR_REPO/om-repository:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' "om-service-container" "$ECR_REPO/om-repository:latest" > imagedefinitions.json
      - ls -la
artifacts:
  files: imagedefinitions.json
